/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleRdRouteImport } from './routes/vehicle-rd'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TechStackRouteImport } from './routes/tech-stack'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as FastChargingRouteImport } from './routes/fast-charging'
import { Route as IndexRouteImport } from './routes/index'

const VehicleRdRoute = VehicleRdRouteImport.update({
  id: '/vehicle-rd',
  path: '/vehicle-rd',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TechStackRoute = TechStackRouteImport.update({
  id: '/tech-stack',
  path: '/tech-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const FastChargingRoute = FastChargingRouteImport.update({
  id: '/fast-charging',
  path: '/fast-charging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fast-charging': typeof FastChargingRoute
  '/franchise': typeof FranchiseRoute
  '/landing': typeof LandingRoute
  '/service': typeof ServiceRoute
  '/tech-stack': typeof TechStackRoute
  '/training': typeof TrainingRoute
  '/vehicle-rd': typeof VehicleRdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fast-charging': typeof FastChargingRoute
  '/franchise': typeof FranchiseRoute
  '/landing': typeof LandingRoute
  '/service': typeof ServiceRoute
  '/tech-stack': typeof TechStackRoute
  '/training': typeof TrainingRoute
  '/vehicle-rd': typeof VehicleRdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fast-charging': typeof FastChargingRoute
  '/franchise': typeof FranchiseRoute
  '/landing': typeof LandingRoute
  '/service': typeof ServiceRoute
  '/tech-stack': typeof TechStackRoute
  '/training': typeof TrainingRoute
  '/vehicle-rd': typeof VehicleRdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fast-charging'
    | '/franchise'
    | '/landing'
    | '/service'
    | '/tech-stack'
    | '/training'
    | '/vehicle-rd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fast-charging'
    | '/franchise'
    | '/landing'
    | '/service'
    | '/tech-stack'
    | '/training'
    | '/vehicle-rd'
  id:
    | '__root__'
    | '/'
    | '/fast-charging'
    | '/franchise'
    | '/landing'
    | '/service'
    | '/tech-stack'
    | '/training'
    | '/vehicle-rd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FastChargingRoute: typeof FastChargingRoute
  FranchiseRoute: typeof FranchiseRoute
  LandingRoute: typeof LandingRoute
  ServiceRoute: typeof ServiceRoute
  TechStackRoute: typeof TechStackRoute
  TrainingRoute: typeof TrainingRoute
  VehicleRdRoute: typeof VehicleRdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-rd': {
      id: '/vehicle-rd'
      path: '/vehicle-rd'
      fullPath: '/vehicle-rd'
      preLoaderRoute: typeof VehicleRdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-stack': {
      id: '/tech-stack'
      path: '/tech-stack'
      fullPath: '/tech-stack'
      preLoaderRoute: typeof TechStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-charging': {
      id: '/fast-charging'
      path: '/fast-charging'
      fullPath: '/fast-charging'
      preLoaderRoute: typeof FastChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FastChargingRoute: FastChargingRoute,
  FranchiseRoute: FranchiseRoute,
  LandingRoute: LandingRoute,
  ServiceRoute: ServiceRoute,
  TechStackRoute: TechStackRoute,
  TrainingRoute: TrainingRoute,
  VehicleRdRoute: VehicleRdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
